package:
  name: eidl7zip
  version: "1.0.0"

build:
  number: 1

source:
  fn: p7zip_16.02_src_all.tar.bz2 [not win]
  url: http://iweb.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_src_all.tar.bz2 [not win]
  md5: a0128d661cfe7cc8c121e73519c54fbf [not win]
  fn: 7za920.zip [win]
  url: https://www.7-zip.org/a/7za920.zip [win]
  md5: 2fac454a90ae96021f4ffc607d4c00f8 [win]


test:
  commands:
    - touch xxx [not win]
    - 7z a xxx.7z xxx [not win]
    - 7za -h [win]

about:
  home: https://github.com/haasad/eidl7zip
  summary: Makes 7zip available cross-platform by packaging 7-zip and p7zip in a single conda package
  license: LGPLv2
  description: |
    # eidl7zip
    This conda package was originally developed for the [EcoInventDownLoader](https://github.com/haasad/EcoInventDownLoader). For Windows it provides the command-line version of [7-zip](https://www.7-zip.org/) (version 9.20), for Linux and OSX [p7zip](https://sourceforge.net/projects/p7zip/) (version 16.02). Both projects are licensed under the [GNU Lesser General Public License v2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html). The conda recipe for this package is available on [github](https://github.com/haasad/eidl7zip).
